In [329]:
import numpy as np
import pandas as pd
from numpy import genfromtxt

In [330]:
df = pd.read_csv('demand_8_12.csv')

In [331]:
df.head()

   FireTruck  Rescue_veh  Water truc  ...          PopupInfo  level  count.1
0          2           1           2  ...  LOW MED HIGH RISE      8        2
1          1           0           0  ...           LOW RISE      0        0
2          1           0           0  ...           LOW RISE      0        0
3          1           0           0  ...           LOW RISE      0        0
4          1           0           0  ...           LOW RISE      0        0

[5 rows x 39 columns]

In [332]:
df['compact'].max()

0.98

In [333]:
df[df['compact'] == df['compact'].max()]

     FireTruck  Rescue_veh  Water truc  ...          PopupInfo  level  count.1
392          4           1           4  ...  LOW MED HIGH RISE     12        3

[1 rows x 39 columns]

In [334]:
df_dem_4_8 = df[['FireTruck','Rescue_veh','Water truc','Ambulance','compact','X','Y']]

In [335]:
df_dem_4_8 = df_dem_4_8.round(4)

In [336]:
df_dem_4_8['X,Y'] = df_dem_4_8[['X', 'Y']].apply(tuple, axis = 1)

In [337]:
df_dem_4_8.head()

   FireTruck  Rescue_veh  Water truc  ...        X        Y                 X,Y
0          2           1           2  ...  72.8352  19.0058  (72.8352, 19.0058)
1          1           0           0  ...  72.8580  19.0062   (72.858, 19.0062)
2          1           0           0  ...  72.8608  19.0061  (72.8608, 19.0061)
3          1           0           0  ...  72.8637  19.0062  (72.8637, 19.0062)
4          1           0           0  ...  72.8609  19.0035  (72.8609, 19.0035)

[5 rows x 8 columns]

In [338]:
df_dem_4_8.head()

   FireTruck  Rescue_veh  Water truc  ...        X        Y                 X,Y
0          2           1           2  ...  72.8352  19.0058  (72.8352, 19.0058)
1          1           0           0  ...  72.8580  19.0062   (72.858, 19.0062)
2          1           0           0  ...  72.8608  19.0061  (72.8608, 19.0061)
3          1           0           0  ...  72.8637  19.0062  (72.8637, 19.0062)
4          1           0           0  ...  72.8609  19.0035  (72.8609, 19.0035)

[5 rows x 8 columns]

In [339]:
df_dem_4_8_vehicle = df_dem_4_8[['FireTruck','Rescue_veh','Water truc','Ambulance']]
df_dem_4_8_vehicle_list = df_dem_4_8_vehicle.values.tolist()

In [340]:
df_dem_4_8['vehicles_list'] = df_dem_4_8_vehicle_list

In [341]:
df1 = pd.read_csv('potential.csv')

In [342]:
df_vehicles = df1[['fire_truck','rescue_tru','water_tank','abulance']]

In [343]:
df_vehicles_list = df_vehicles.values.tolist()

In [344]:
df1['vehicles_list'] = df_vehicles_list

In [345]:
df1.head()

   fire_truck  rescue_tru  water_tank  ...  ID  Fixed  vehicles_list
0           1           1           1  ...   0     No   [1, 1, 1, 1]
1           1           1           1  ...   1     No   [1, 1, 1, 1]
2           1           1           1  ...   2     No   [1, 1, 1, 1]
3           1           1           1  ...   3     No   [1, 1, 1, 1]
4           1           1           1  ...   4     No   [1, 1, 1, 1]

[5 rows x 10 columns]

In [346]:
df_dem_4_8.head()

   FireTruck  Rescue_veh  Water truc  ...        Y                 X,Y  vehicles_list
0          2           1           2  ...  19.0058  (72.8352, 19.0058)   [2, 1, 2, 0]
1          1           0           0  ...  19.0062   (72.858, 19.0062)   [1, 0, 0, 0]
2          1           0           0  ...  19.0061  (72.8608, 19.0061)   [1, 0, 0, 0]
3          1           0           0  ...  19.0062  (72.8637, 19.0062)   [1, 0, 0, 0]
4          1           0           0  ...  19.0035  (72.8609, 19.0035)   [1, 0, 0, 0]

[5 rows x 9 columns]

In [347]:
df1_location = df1.copy()

In [348]:
#round x and y to four decimal places
df1_location = df1_location.round(4)

In [349]:
df1_location.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 432 entries, 0 to 431
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   fire_truck     432 non-null    int64
 1   rescue_tru     432 non-null    int64
 2   water_tank     432 non-null    int64
 3   abulance       432 non-null    int64
 4   Total          432 non-null    int64
 5   Y              432 non-null    float64
 6   X              432 non-null    float64
 7   ID             432 non-null    int64
 8   Fixed          432 non-null    object
 9   vehicles_list  432 non-null    object
dtypes: float64(2), int64(6), object(2)
memory usage: 33.9+ KB

In [350]:
df1_location["location"] = df1_location[["X","Y"]].apply(tuple, axis=1)

In [351]:
df1_location.head()

   fire_truck  rescue_tru  water_tank  ...  Fixed  vehicles_list            location
0           1           1           1  ...     No   [1, 1, 1, 1]  (72.8352, 19.0059)
1           1           1           1  ...     No   [1, 1, 1, 1]   (72.858, 19.0061)
2           1           1           1  ...     No   [1, 1, 1, 1]  (72.8608, 19.0062)
3           1           1           1  ...     No   [1, 1, 1, 1]  (72.8609, 19.0034)
4           1           1           1  ...     No   [1, 1, 1, 1]  (72.8125, 19.0002)

[5 rows x 11 columns]

In [352]:
df1_location['Fixed'] = df1_location['Fixed'].astype('category')

In [353]:
df1_location['Fixed'] = df1_location['Fixed'].cat.codes

In [354]:
df1_location.head()

   fire_truck  rescue_tru  water_tank  ...  Fixed  vehicles_list            location
0           1           1           1  ...      0   [1, 1, 1, 1]  (72.8352, 19.0059)
1           1           1           1  ...      0   [1, 1, 1, 1]   (72.858, 19.0061)
2           1           1           1  ...      0   [1, 1, 1, 1]  (72.8608, 19.0062)
3           1           1           1  ...      0   [1, 1, 1, 1]  (72.8609, 19.0034)
4           1           1           1  ...      0   [1, 1, 1, 1]  (72.8125, 19.0002)

[5 rows x 11 columns]

In [355]:
df1_location.shape

(432, 11)

In [356]:
df_dem_4_8.shape

(464, 9)

In [357]:
df_dem_4_8.head()

   FireTruck  Rescue_veh  Water truc  ...        Y                 X,Y  vehicles_list
0          2           1           2  ...  19.0058  (72.8352, 19.0058)   [2, 1, 2, 0]
1          1           0           0  ...  19.0062   (72.858, 19.0062)   [1, 0, 0, 0]
2          1           0           0  ...  19.0061  (72.8608, 19.0061)   [1, 0, 0, 0]
3          1           0           0  ...  19.0062  (72.8637, 19.0062)   [1, 0, 0, 0]
4          1           0           0  ...  19.0035  (72.8609, 19.0035)   [1, 0, 0, 0]

[5 rows x 9 columns]

In [358]:
df_dem_4_8['potential'] = ""

In [359]:
df_dem_4_8.head()

   FireTruck  Rescue_veh  ...  vehicles_list  potential
0          2           1  ...   [2, 1, 2, 0]
1          1           0  ...   [1, 0, 0, 0]
2          1           0  ...   [1, 0, 0, 0]
3          1           0  ...   [1, 0, 0, 0]
4          1           0  ...   [1, 0, 0, 0]

[5 rows x 10 columns]

In [360]:
df_dem_4_8.shape

(464, 10)

In [361]:
data_4_8 = genfromtxt('12_16.csv', delimiter=',') #loading the 4_8 timetravel dataset

In [362]:
data_4_8.shape

(464, 432)

In [363]:
row_list = np.where(np.any(data_4_8 == float(1), axis = 1))

In [364]:
rows = df_dem_4_8.index.values

In [365]:
rows = list(rows)

In [366]:
row_list = list(row_list)

In [367]:
new_array = data_4_8.min(1)

In [368]:
new_array_list = list(new_array)

In [369]:
len(new_array_list)

464

In [370]:
for x,i in enumerate(new_array_list):
  if i == 1:
    df_dem_4_8['potential'][x] = 1
  else:
    df_dem_4_8['potential'][x] = 0

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """

In [371]:
df_dem_4_8.head()

   FireTruck  Rescue_veh  ...  vehicles_list  potential
0          2           1  ...   [2, 1, 2, 0]          1
1          1           0  ...   [1, 0, 0, 0]          1
2          1           0  ...   [1, 0, 0, 0]          1
3          1           0  ...   [1, 0, 0, 0]          0
4          1           0  ...   [1, 0, 0, 0]          1

[5 rows x 10 columns]

In [372]:
df_dem_4_8['potential'].sum()

432

In [373]:
df_dem_4_8.index.name = 'Index'

In [374]:
df_dem_4_8.head()

       FireTruck  Rescue_veh  ...  vehicles_list  potential
Index                         ...
0              2           1  ...   [2, 1, 2, 0]          1
1              1           0  ...   [1, 0, 0, 0]          1
2              1           0  ...   [1, 0, 0, 0]          1
3              1           0  ...   [1, 0, 0, 0]          0
4              1           0  ...   [1, 0, 0, 0]          1

[5 rows x 10 columns]

In [375]:
df_dem_4_8_edit = df_dem_4_8[['X,Y', 'vehicles_list', 'potential']]

In [376]:
df_dem_4_8_edit.shape

(464, 3)

In [377]:
df_dem_4_8_edit.head()

                      X,Y vehicles_list potential
Index
0      (72.8352, 19.0058)  [2, 1, 2, 0]         1
1       (72.858, 19.0062)  [1, 0, 0, 0]         1
2      (72.8608, 19.0061)  [1, 0, 0, 0]         1
3      (72.8637, 19.0062)  [1, 0, 0, 0]         0
4      (72.8609, 19.0035)  [1, 0, 0, 0]         1

In [378]:
df_dem_4_8_edit.to_csv('d_8_12.csv')